### ISSUE TITLE
Implement site setting for JIT

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#1]

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/Vanadium/blob/11/patches/0078-JIT-less-toggle.patch

**Comment by qua3k** [comment]
Vanadium: https://gist.github.com/qua3k/80b558b83e9dca1dc20cb922020f8288

**Comment by qua3k** [comment]
This issue is now for the site setting

**Comment by quh4gko8** [comment]
To investigate: have the page info in c/c++ side read the  site exceptions on its domain instead of the host/origin itself to reduce the needed exceptions to be set/fetched.

Instantiating a GURL with the domain pattern to get the content setting value (whether a content setting exception like Javascript, Cookies,...) does not work

See https://source.chromium.org/chromium/chromium/src/+/main:components/page_info/page_info.cc;l=909?q=page_info.cc

**Comment by qua3k** [comment]
It's worth investigating hooking into the site engagement logic and disabling/enabling mitigations on a per-site basis like Edge is currently doing.
