### ISSUE TITLE
Harden PartitionAlloc

### ISSUE THREAD

**Issue by qua3k** [Hexavalent-Browser/Hexavalent#54]
This issue will be tracking the improvements we are making to PartitionAlloc.

* [ ] Randomized trailing cookie zeroing the leading byte to terminate C string overflows and absorb other small overflows
* [ ] Replacement of DCHECKs with CHECKs to induce crashes instead of exposing the user to potential vulnerabilities
* [x] Consistent zero-based or pattern-based sanitization on free depending on build setup to get sensitive data out of the process as soon as possible and mitigate some forms of use-after-free
* [ ] Enablement of various security features that were deemed too expensive for release builds
* [ ] Improved pointer obfuscation inspired by Linux's SLAB_FREELIST_HARDENED to protect from complete overwrites

**Comment by Seirdy** [comment]
Is there an upstreaming plan? I see some options:

- Implement this in Vanadium, bring the change downstream to Hexavalent
- Implement in Hexavalent, upstream to Vanadium
- Send patches to the Chromium project in parallel with the above options; if they accept, that's one less patch to handle here.

**Comment by qua3k** [comment]
Vanadium isn’t going to be bundling its own hardened allocator because GrapheneOS already provides hardened_malloc as part of the OS. Our efforts to upstream might not bd accepted because they’re much more sensitive to performance than we are.

**Comment by qua3k** [comment]
Vanadium uses PartitionAlloc.

**Comment by Seirdy** [comment]
Might be worth reaching out to @struct who's familiar with PartitionAlloc hardening, having made both https://github.com/struct/isoalloc and https://github.com/struct/HardenedPartitionAlloc (the former of which is based on PartitionAlloc)

**Comment by qua3k** [comment]
Mf really just pinged Chris

**Comment by struct** [comment]
Hello! I don't have a lot of context here but thought I'd offer my 2 cents:

> * Send patches to the Chromium project in parallel with the above options; if they accept, that's one less patch to handle here.
I haven't worked on the HPA fork in a few years and have no plans to again. The PA code has significantly changed since then so you will definitely want to get an idea of what its current security properties are and whats missing. My HPA hardening patches were mostly for POC purposes and did not take performance into consideration. You might have luck writing performant versions of them and attempting to upstream them one at a time. Indeed the Chrome team is very sensitive to performance issues. I don't know what targets your Vanadium project targets but it's possible you will have a more narrow set of constraints and can get away with more performance regressions.
