### ISSUE TITLE
Arch packaging

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#7]

**Comment by AkechiShiro** [comment]
Can I take this issue as my first issue? I already manage few package in the AUR (Arch User Repositories) for Arch Linux.

**Comment by Zanthed** [comment]
I think @Douloureux made a not-yet-ready PKGBUILD. Could work with them.

**Comment by AkechiShiro** [comment]
I can get started from scratch if needed, the project is probably built using `cmake` or something alike, but the patches needs to be applied before building I suppose.

**Comment by AkechiShiro** [comment]
This could be a starting point as well : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ungoogled-chromium I believe, from there I could make iterations and put the patches contained in Hexavalent's repo.

**Comment by Douloureux** [comment]
I made a PKGBUILD for a binary version, piggybacking off of the RPM that Hexavalent already provides.

**Comment by Douloureux** [comment]
> This could be a starting point as well : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ungoogled-chromium I believe, from there I could make iterations and put the patches contained in Hexavalent's repo.

Yes, this is seems good, but Hexavalent installs to different locations, unpacking <a href='https://dl.hexavalent.org/linux/hexavalent-browser/hexavalent-browser-stable-101.0.4951.41-1.x86_64.rpm'>this</a> should give you an idea. Ignore the cron.daily folder, since that is RPM distro exclusive. I'd be happy to work with you on this.

**Comment by AkechiShiro** [comment]
Do you know what kind of patches/minimal patches that are needed for the sources inside the PKGBUILD, that should be applied before building?

**Comment by flawedworld** [comment]
The Arch PKGBUILD show be just extracting the rpm or deb make by the chromium build system and reusing the files within the former.

**Comment by AkechiShiro** [comment]
Thanks, I got it I thought maybe it was gonna need to be more granular but installing the files so that in case more patches are added or may be removed from the build script, but from the rpm/deb is easier and the same package will be distributed to all distros kind of like a reproducible builds if that is aimed for I guess, will work on something that works then.

I was just not sure to do that since it wasn't recommended in this forum :
https://bbs.archlinux.org/viewtopic.php?id=210629 on a similar topic but for now considering the very early state of the project I believe it's fine for now.

**Comment by Douloureux** [comment]
```sh
pkgname=hexavalent
pkgver=101.0.4951.41
pkgrel=1
pkgdesc='Hexavalent Browser'
arch=('x86_64')
url="https://hexavalent.org"
license=('BSD Clause Clear')
provides=('hexavalent')
conflicts=('hexavalent')
depends=('ffmpeg' 'pipewire' 're2' 'snappy' 'minizip')
options=('!emptydirs' '!strip')

source=('https://dl.hexavalent.org/linux/hexavalent-browser/hexavalent-browser-stable-101.0.4951.41-1.x86_64.rpm')

sha256sums=('c481603c8c2f1f3a9e2803a328b709801c07bfbe9767350804b166c126dfa39c')

package() (
    mkdir -p "${pkgdir}/usr/share/"
    mkdir -p "${pkgdir}/opt/hexavalent"
    mkdir -p "${pkgdir}/usr/bin/"
    cp -r "${srcdir}/usr/share/." "${pkgdir}/usr/share/"
    cp -r "${srcdir}/opt/hexavalent/." "${pkgdir}/opt/hexavalent"
    cp -r "${srcdir}/usr/bin/." "${pkgdir}/usr/bin/"
    ln -s "usr/bin/hexavalent-browser-stable" "${pkgdir}/usr/bin/hexavalent"
    sudo chown root "${srcdir}/opt/hexavalent/chrome-sandbox"
    sudo chmod 4775 "${srcdir}/opt/hexavalent/chrome-sandbox"
)
```
That is the current one, the Hexavalent.desktop file needs tweaking for the logos and all, can be dealt with after the RPM officially releases

**Comment by flawedworld** [comment]
Note that we aren't going to release in the AUR, we are going to release our own repo.
